services:
  - type: web
    name: fairdraw
    repo: https://github.com/viks93/fairdraw
    runtime: docker
    branch: main
    plan: free
    healthCheckPath: /
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: DATABASE_URL
        sync: false
